parameters:
  jobName: '' # name for each build job - needs to be unique within a given stage/pipeline

jobs:
- job: ${{ parameters.jobName }}
  displayName: 'Import container'
  steps:

  - download: current # download pipeline artifacts

  - template: steps-buildagent-prerequisites.yaml

  - task: AzureCLI@2
    displayName: 'Import container images'
    retryCountOnTaskFailure: 1
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |

        # Login to ACR
        az acr login -n $acrName

        $importContainers = Get-Content /.ado/pipelines/config/import-containers.json | ConvertFrom-JSON

        foreach ($container in $importContainers) {        

          az acr import --name $acrName `
            --source "$($container.registry)/$($container.image):$($container.tag)" `
            --image "$($container.image):$($container.tag)"
        }
