workload:
  domainname: "OVERWRITE-cluster.eastus2.cloudapp.azure.com"

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "cert-manager-alwayson"

azure:
  baseurl: "OVERWRITE.myalwaysonapp.net" # FQDN used by the Azure Front Door endpoint
